apiVersion: v2
name: tech-ops-docs
description: Technical Operations Documentation — static site served by nginx
type: application
version: 0.3.0 # x-release-please-version
appVersion: "0.3.0" # x-release-please-version
